// Datos base precargados de la programación académica (128 grupos)
const DEMO_GRUPOS_DATA = [
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "ALGORITMOS Y PROGRAMACIÓN",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 0,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "ALGORITMOS Y PROGRAMACIÓN",
    "seccion": "B1",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 1,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "ALGORITMOS Y PROGRAMACIÓN",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 2,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "ALGORITMOS Y PROGRAMACIÓN",
    "seccion": "B2",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 3,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "ALGORITMOS Y PROGRAMACIÓN",
    "seccion": "B3",
    "tipo_grupo": "TEORIA",
    "matriculados": 46,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 4,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "ALGORITMOS Y PROGRAMACIÓN",
    "seccion": "B3",
    "tipo_grupo": "PRACTICA",
    "matriculados": 46,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 5,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 6,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B1",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 7,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 62,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "07-12-2026",
    "termino": "02-01-2027",
    "id": 8,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B2",
    "tipo_grupo": "PRACTICA",
    "matriculados": 62,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 9,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 53,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 10,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B1",
    "tipo_grupo": "PRACTICA",
    "matriculados": 53,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 11,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 55,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 12,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B2",
    "tipo_grupo": "PRACTICA",
    "matriculados": 55,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 13,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "FUNDAMENTOS DE MODELADO Y ANIMACIÓN",
    "seccion": "B10",
    "tipo_grupo": "TEORIA",
    "matriculados": 45,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 14,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "FUNDAMENTOS DE MODELADO Y ANIMACIÓN",
    "seccion": "B10",
    "tipo_grupo": "PRACTICA",
    "matriculados": 45,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 15,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "FUNDAMENTOS DE MODELADO Y ANIMACIÓN",
    "seccion": "B11",
    "tipo_grupo": "TEORIA",
    "matriculados": 45,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 16,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "FUNDAMENTOS DE MODELADO Y ANIMACIÓN",
    "seccion": "B11",
    "tipo_grupo": "PRACTICA",
    "matriculados": 45,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 17,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "FUNDAMENTOS DE MODELADO Y ANIMACIÓN",
    "seccion": "B12",
    "tipo_grupo": "TEORIA",
    "matriculados": 14,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 18,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "FUNDAMENTOS DE MODELADO Y ANIMACIÓN",
    "seccion": "B12",
    "tipo_grupo": "PRACTICA",
    "matriculados": 14,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 19,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B10",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "ANTEZANA ELORRIETA ANGEL ESTUARD",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 20,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B11",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "ANTEZANA ELORRIETA ANGEL ESTUARD",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 21,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B10",
    "tipo_grupo": "TEORIA",
    "matriculados": 27,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 22,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B10",
    "tipo_grupo": "PRACTICA",
    "matriculados": 27,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 23,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B11",
    "tipo_grupo": "TEORIA",
    "matriculados": 42,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 24,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA DE SISTEMAS",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B11",
    "tipo_grupo": "PRACTICA",
    "matriculados": 42,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 25,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 26,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B1",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 27,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 62,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 28,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B2",
    "tipo_grupo": "PRACTICA",
    "matriculados": 62,
    "docente": "MURO NUÑEZ EFRAIN ALEJANDRO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 29,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B3",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 30,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B3",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 31,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B4",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 32,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B4",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AMACHE SANCHEZ MILTON FREDDY",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 33,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B5",
    "tipo_grupo": "TEORIA",
    "matriculados": 63,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 34,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B5",
    "tipo_grupo": "PRACTICA",
    "matriculados": 63,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 35,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B6",
    "tipo_grupo": "TEORIA",
    "matriculados": 62,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "07-12-2026",
    "termino": "09-01-2027",
    "id": 36,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B6",
    "tipo_grupo": "PRACTICA",
    "matriculados": 62,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 37,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B7",
    "tipo_grupo": "TEORIA",
    "matriculados": 63,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 38,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B7",
    "tipo_grupo": "PRACTICA",
    "matriculados": 63,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 39,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B8",
    "tipo_grupo": "TEORIA",
    "matriculados": 37,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 40,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "EXPRESIÓN GRÁFICA",
    "seccion": "B8",
    "tipo_grupo": "PRACTICA",
    "matriculados": 37,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 41,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 42,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B1",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 43,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 44,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B2",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 45,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B3",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 46,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B3",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 47,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B4",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 48,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B4",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AYALA RIVERA JUAN CARLOS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 49,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B5",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 50,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B5",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 51,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B6",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 52,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B6",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 53,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B7",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 54,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B7",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 55,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B8",
    "tipo_grupo": "TEORIA",
    "matriculados": 13,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 56,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 2,
    "curso": "QUÍMICA GENERAL",
    "seccion": "B8",
    "tipo_grupo": "PRACTICA",
    "matriculados": 13,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 57,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B10",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "MARTINEZ JIMENEZ SANDOR LENIN",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 58,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B10",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "MARTINEZ JIMENEZ SANDOR LENIN",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 59,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B11",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "MARTINEZ JIMENEZ SANDOR LENIN",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 60,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B11",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "MARTINEZ JIMENEZ SANDOR LENIN",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 61,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B12",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 62,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B12",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 63,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B13",
    "tipo_grupo": "TEORIA",
    "matriculados": 61,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 64,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B13",
    "tipo_grupo": "PRACTICA",
    "matriculados": 61,
    "docente": "GUTIERREZ MENDOZA ALICIA YANETT",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 65,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B14",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "CASTILLO CHALCO ISAAC DUHAMEL",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 66,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B14",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "CASTILLO CHALCO ISAAC DUHAMEL",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 67,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B15",
    "tipo_grupo": "TEORIA",
    "matriculados": 40,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 68,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B15",
    "tipo_grupo": "PRACTICA",
    "matriculados": 40,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 69,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B16",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 70,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B16",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 71,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B17",
    "tipo_grupo": "TEORIA",
    "matriculados": 35,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 72,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "CREATIVIDAD E INNOVACIÓN",
    "seccion": "B17",
    "tipo_grupo": "PRACTICA",
    "matriculados": 35,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 73,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B10",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 74,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B10",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 75,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B11",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 76,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B11",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 77,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B12",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 78,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B12",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 79,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B13",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 80,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B13",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "ROJAS HURTADO JENNIFER IRAIDA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 81,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B14",
    "tipo_grupo": "TEORIA",
    "matriculados": 40,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 82,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "ECONOMÍA Y FINANZAS ",
    "seccion": "B14",
    "tipo_grupo": "PRACTICA",
    "matriculados": 40,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 83,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "LEWIS DIAZ ARTURO FEDERICO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 84,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "LEWIS DIAZ ARTURO FEDERICO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 85,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B3",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "LEWIS DIAZ ARTURO FEDERICO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 86,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B4",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "LEWIS DIAZ ARTURO FEDERICO",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 87,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B5",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 88,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B6",
    "tipo_grupo": "TEORIA",
    "matriculados": 59,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 89,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 3,
    "curso": "MATEMÁTICA PARA LA INGENIERÍA ",
    "seccion": "B7",
    "tipo_grupo": "TEORIA",
    "matriculados": 36,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 90,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CÁLCULO INTEGRAL Y ECUACIONES DIFERENCIALES ",
    "seccion": "B10",
    "tipo_grupo": "TEORIA",
    "matriculados": 61,
    "docente": "LEEN CUEVA CHRISTIAN NICOLAS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 91,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CÁLCULO INTEGRAL Y ECUACIONES DIFERENCIALES ",
    "seccion": "B11",
    "tipo_grupo": "TEORIA",
    "matriculados": 0,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "08-11-2026",
    "id": 92,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CÁLCULO INTEGRAL Y ECUACIONES DIFERENCIALES ",
    "seccion": "B12",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "BRINGAS QUESQUEN PAULO CESAR",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 93,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CÁLCULO INTEGRAL Y ECUACIONES DIFERENCIALES ",
    "seccion": "B13",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "LEEN CUEVA CHRISTIAN NICOLAS",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 94,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CÁLCULO INTEGRAL Y ECUACIONES DIFERENCIALES ",
    "seccion": "B14",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "BRINGAS QUESQUEN PAULO CESAR",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 95,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CÁLCULO INTEGRAL Y ECUACIONES DIFERENCIALES ",
    "seccion": "B15",
    "tipo_grupo": "TEORIA",
    "matriculados": 15,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 96,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CONTABILIDAD GERENCIAL Y COSTOS",
    "seccion": "B20",
    "tipo_grupo": "TEORIA",
    "matriculados": 63,
    "docente": "MARIN LOZANO RICHAR ALEXANDER",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 97,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CONTABILIDAD GERENCIAL Y COSTOS",
    "seccion": "B20",
    "tipo_grupo": "PRACTICA",
    "matriculados": 63,
    "docente": "MARIN LOZANO RICHAR ALEXANDER",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 98,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CONTABILIDAD GERENCIAL Y COSTOS",
    "seccion": "B21",
    "tipo_grupo": "TEORIA",
    "matriculados": 39,
    "docente": "MARIN LOZANO RICHAR ALEXANDER",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 99,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CONTABILIDAD GERENCIAL Y COSTOS",
    "seccion": "B21",
    "tipo_grupo": "PRACTICA",
    "matriculados": 39,
    "docente": "MARIN LOZANO RICHAR ALEXANDER",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 100,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CONTABILIDAD GERENCIAL Y COSTOS",
    "seccion": "B22",
    "tipo_grupo": "TEORIA",
    "matriculados": 17,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "07-12-2026",
    "termino": "09-01-2027",
    "id": 101,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "CONTABILIDAD GERENCIAL Y COSTOS",
    "seccion": "B22",
    "tipo_grupo": "PRACTICA",
    "matriculados": 17,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 102,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B20",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "BRINGAS QUESQUEN PAULO CESAR",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 103,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B20",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 104,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B21",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 105,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B21",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 106,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B22",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 107,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B22",
    "tipo_grupo": "PRACTICA",
    "matriculados": 60,
    "docente": "AGREDA PALOMINO RICARDO NOE",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 108,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B23",
    "tipo_grupo": "TEORIA",
    "matriculados": 30,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 109,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 4,
    "curso": "FÍSICA GENERAL",
    "seccion": "B23",
    "tipo_grupo": "PRACTICA",
    "matriculados": 30,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 110,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ACCESIBILIDAD Y DISEÑO UNIVERSAL",
    "seccion": "B20",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "VIGO ALVA KATTY VANESA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 111,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ACCESIBILIDAD Y DISEÑO UNIVERSAL",
    "seccion": "B22",
    "tipo_grupo": "TEORIA",
    "matriculados": 60,
    "docente": "VIGO ALVA KATTY VANESA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 112,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ACCESIBILIDAD Y DISEÑO UNIVERSAL",
    "seccion": "B23",
    "tipo_grupo": "TEORIA",
    "matriculados": 16,
    "docente": "",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 113,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ESTUDIO DEL TRABAJO",
    "seccion": "B20",
    "tipo_grupo": "TEORIA",
    "matriculados": 27,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 114,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ESTUDIO DEL TRABAJO",
    "seccion": "B20",
    "tipo_grupo": "PRACTICA",
    "matriculados": 27,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 115,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ESTUDIO DEL TRABAJO",
    "seccion": "B21",
    "tipo_grupo": "TEORIA",
    "matriculados": 34,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "06-12-2026",
    "termino": "28-12-2026",
    "id": 116,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "ESTUDIO DEL TRABAJO",
    "seccion": "B21",
    "tipo_grupo": "PRACTICA",
    "matriculados": 34,
    "docente": "OLMOS SALDIVAR DAVID",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 117,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "INVESTIGACIÓN DE OPERACIONES",
    "seccion": "B1",
    "tipo_grupo": "TEORIA",
    "matriculados": 27,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 118,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "INVESTIGACIÓN DE OPERACIONES",
    "seccion": "B1",
    "tipo_grupo": "PRACTICA",
    "matriculados": 27,
    "docente": "ARCE VILLANUEVA CHRISTIAN ANTHONY",
    "vbda": "NO",
    "vbdg": "NO",
    "aprobado": "NO",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 119,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "INVESTIGACIÓN DE OPERACIONES",
    "seccion": "B2",
    "tipo_grupo": "TEORIA",
    "matriculados": 61,
    "docente": "VIGO ALVA KATTY VANESA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-12-2026",
    "termino": "09-01-2027",
    "id": 120,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 5,
    "curso": "INVESTIGACIÓN DE OPERACIONES",
    "seccion": "B2",
    "tipo_grupo": "PRACTICA",
    "matriculados": 61,
    "docente": "VIGO ALVA KATTY VANESA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "14-12-2026",
    "termino": "28-12-2026",
    "id": 121,
    "modulo": "Dic"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 6,
    "curso": "ERGONOMÍA, SEGURIDAD Y SALUD OCUPACIONAL",
    "seccion": "B60",
    "tipo_grupo": "TEORIA",
    "matriculados": 19,
    "docente": "HERMOZA MEDINA RENZO ALEXANDER",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "01-09-2026",
    "termino": "03-10-2026",
    "id": 122,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 6,
    "curso": "ERGONOMÍA, SEGURIDAD Y SALUD OCUPACIONAL",
    "seccion": "B60",
    "tipo_grupo": "PRACTICA",
    "matriculados": 19,
    "docente": "HERMOZA MEDINA RENZO ALEXANDER",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "07-09-2026",
    "termino": "21-09-2026",
    "id": 123,
    "modulo": "Set"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 6,
    "curso": "SIMULACIÓN E INTELIGENCIA DE DATOS",
    "seccion": "B60",
    "tipo_grupo": "TEORIA",
    "matriculados": 39,
    "docente": "",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "04-10-2026",
    "termino": "26-10-2026",
    "id": 124,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 6,
    "curso": "SIMULACIÓN E INTELIGENCIA DE DATOS",
    "seccion": "B60",
    "tipo_grupo": "PRACTICA",
    "matriculados": 39,
    "docente": "RIVERA RAMIREZ YDANIA VANESSA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "12-10-2026",
    "termino": "26-10-2026",
    "id": 125,
    "modulo": "Oct"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 6,
    "curso": "TECNOLOGÍA Y SISTEMAS DE PRODUCCIÓN",
    "seccion": "B60",
    "tipo_grupo": "TEORIA",
    "matriculados": 24,
    "docente": "",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "02-11-2026",
    "termino": "05-12-2026",
    "id": 126,
    "modulo": "Nov"
  },
  {
    "escuela": "INGENIERIA INDUSTRIAL",
    "ciclo": 6,
    "curso": "TECNOLOGÍA Y SISTEMAS DE PRODUCCIÓN",
    "seccion": "B60",
    "tipo_grupo": "PRACTICA",
    "matriculados": 24,
    "docente": "RIVERA RAMIREZ YDANIA VANESSA",
    "vbda": "SI",
    "vbdg": "SI",
    "aprobado": "SI",
    "inicio": "09-11-2026",
    "termino": "23-11-2026",
    "id": 127,
    "modulo": "Nov"
  }
];
